# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import meeting_pb2 as meeting__pb2


class MeetingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMeeting = channel.unary_unary(
                '/meeting.MeetingService/CreateMeeting',
                request_serializer=meeting__pb2.CreateMeetingRequest.SerializeToString,
                response_deserializer=meeting__pb2.MeetingResponse.FromString,
                )
        self.JoinMeeting = channel.unary_unary(
                '/meeting.MeetingService/JoinMeeting',
                request_serializer=meeting__pb2.JoinMeetingRequest.SerializeToString,
                response_deserializer=meeting__pb2.JoinMeetingResponse.FromString,
                )
        self.LeaveMeeting = channel.unary_unary(
                '/meeting.MeetingService/LeaveMeeting',
                request_serializer=meeting__pb2.LeaveMeetingRequest.SerializeToString,
                response_deserializer=meeting__pb2.StatusResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/meeting.MeetingService/SendMessage',
                request_serializer=meeting__pb2.MessageRequest.SerializeToString,
                response_deserializer=meeting__pb2.StatusResponse.FromString,
                )
        self.GetMessages = channel.unary_unary(
                '/meeting.MeetingService/GetMessages',
                request_serializer=meeting__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=meeting__pb2.MessageListResponse.FromString,
                )
        self.StreamMessages = channel.unary_stream(
                '/meeting.MeetingService/StreamMessages',
                request_serializer=meeting__pb2.StreamMessagesRequest.SerializeToString,
                response_deserializer=meeting__pb2.MessageResponse.FromString,
                )
        self.SendWebRTCSignal = channel.unary_unary(
                '/meeting.MeetingService/SendWebRTCSignal',
                request_serializer=meeting__pb2.WebRTCSignalRequest.SerializeToString,
                response_deserializer=meeting__pb2.StatusResponse.FromString,
                )
        self.StreamWebRTCSignals = channel.unary_stream(
                '/meeting.MeetingService/StreamWebRTCSignals',
                request_serializer=meeting__pb2.StreamSignalsRequest.SerializeToString,
                response_deserializer=meeting__pb2.WebRTCSignalResponse.FromString,
                )
        self.UpdateParticipantStatus = channel.unary_unary(
                '/meeting.MeetingService/UpdateParticipantStatus',
                request_serializer=meeting__pb2.ParticipantStatusRequest.SerializeToString,
                response_deserializer=meeting__pb2.StatusResponse.FromString,
                )
        self.GetParticipants = channel.unary_unary(
                '/meeting.MeetingService/GetParticipants',
                request_serializer=meeting__pb2.GetParticipantsRequest.SerializeToString,
                response_deserializer=meeting__pb2.ParticipantListResponse.FromString,
                )
        self.EndMeeting = channel.unary_unary(
                '/meeting.MeetingService/EndMeeting',
                request_serializer=meeting__pb2.EndMeetingRequest.SerializeToString,
                response_deserializer=meeting__pb2.StatusResponse.FromString,
                )


class MeetingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMeeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinMeeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveMeeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWebRTCSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWebRTCSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateParticipantStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParticipants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndMeeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeetingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMeeting,
                    request_deserializer=meeting__pb2.CreateMeetingRequest.FromString,
                    response_serializer=meeting__pb2.MeetingResponse.SerializeToString,
            ),
            'JoinMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinMeeting,
                    request_deserializer=meeting__pb2.JoinMeetingRequest.FromString,
                    response_serializer=meeting__pb2.JoinMeetingResponse.SerializeToString,
            ),
            'LeaveMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveMeeting,
                    request_deserializer=meeting__pb2.LeaveMeetingRequest.FromString,
                    response_serializer=meeting__pb2.StatusResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=meeting__pb2.MessageRequest.FromString,
                    response_serializer=meeting__pb2.StatusResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=meeting__pb2.GetMessagesRequest.FromString,
                    response_serializer=meeting__pb2.MessageListResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=meeting__pb2.StreamMessagesRequest.FromString,
                    response_serializer=meeting__pb2.MessageResponse.SerializeToString,
            ),
            'SendWebRTCSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWebRTCSignal,
                    request_deserializer=meeting__pb2.WebRTCSignalRequest.FromString,
                    response_serializer=meeting__pb2.StatusResponse.SerializeToString,
            ),
            'StreamWebRTCSignals': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWebRTCSignals,
                    request_deserializer=meeting__pb2.StreamSignalsRequest.FromString,
                    response_serializer=meeting__pb2.WebRTCSignalResponse.SerializeToString,
            ),
            'UpdateParticipantStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParticipantStatus,
                    request_deserializer=meeting__pb2.ParticipantStatusRequest.FromString,
                    response_serializer=meeting__pb2.StatusResponse.SerializeToString,
            ),
            'GetParticipants': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParticipants,
                    request_deserializer=meeting__pb2.GetParticipantsRequest.FromString,
                    response_serializer=meeting__pb2.ParticipantListResponse.SerializeToString,
            ),
            'EndMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.EndMeeting,
                    request_deserializer=meeting__pb2.EndMeetingRequest.FromString,
                    response_serializer=meeting__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meeting.MeetingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeetingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/CreateMeeting',
            meeting__pb2.CreateMeetingRequest.SerializeToString,
            meeting__pb2.MeetingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/JoinMeeting',
            meeting__pb2.JoinMeetingRequest.SerializeToString,
            meeting__pb2.JoinMeetingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/LeaveMeeting',
            meeting__pb2.LeaveMeetingRequest.SerializeToString,
            meeting__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/SendMessage',
            meeting__pb2.MessageRequest.SerializeToString,
            meeting__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/GetMessages',
            meeting__pb2.GetMessagesRequest.SerializeToString,
            meeting__pb2.MessageListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/meeting.MeetingService/StreamMessages',
            meeting__pb2.StreamMessagesRequest.SerializeToString,
            meeting__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendWebRTCSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/SendWebRTCSignal',
            meeting__pb2.WebRTCSignalRequest.SerializeToString,
            meeting__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamWebRTCSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/meeting.MeetingService/StreamWebRTCSignals',
            meeting__pb2.StreamSignalsRequest.SerializeToString,
            meeting__pb2.WebRTCSignalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateParticipantStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/UpdateParticipantStatus',
            meeting__pb2.ParticipantStatusRequest.SerializeToString,
            meeting__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetParticipants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/GetParticipants',
            meeting__pb2.GetParticipantsRequest.SerializeToString,
            meeting__pb2.ParticipantListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meeting.MeetingService/EndMeeting',
            meeting__pb2.EndMeetingRequest.SerializeToString,
            meeting__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
