"""Autogenerated migration: add missing simple columns to `user` table

Revision ID: autogen_20251017062127_2234014b
Revises: 04261a04e3fc
Create Date: 2025-10-17T06:21:27.990991
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'autogen_20251017062127_2234014b'
down_revision = '04261a04e3fc'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column('dob', sa.String(length=10), nullable=True))


def downgrade():
    op.drop_column('user', 'dob')
