"""removed the dob

Revision ID: e32fad9e30c6
Revises: autogen_20251017062127_2234014b
Create Date: 2025-10-17 12:10:15.227987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32fad9e30c6'
down_revision = 'autogen_20251017062127_2234014b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addon', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_addon_venue_id'), 'addon', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'addon', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'addon', type_='foreignkey')
    op.drop_index(op.f('ix_addon_venue_id'), table_name='addon')
    op.drop_column('addon', 'venue_id')
    # ### end Alembic commands ###